In [1]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array

In [47]:
inputs1 = Input(shape=(5, 1))
lstm1, state_h, state_c = LSTM(3, return_sequences=True, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
model.summary()

Model: "model_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_23 (InputLayer)        [(None, 5, 1)]            0         
_________________________________________________________________
lstm_23 (LSTM)               [(None, 5, 3), (None, 3), 60        
Total params: 60
Trainable params: 60
Non-trainable params: 0
_________________________________________________________________


In [48]:
data = array([0.1, 0.2, 0.3, 0, 0]).reshape((1,5,1))
model.predict(data)

[array([[[-0.01265856, -0.01433322, -0.00649217],
         [-0.03355659, -0.03692929, -0.01607281],
         [-0.05981635, -0.06354216, -0.02673116],
         [-0.04053011, -0.04873908, -0.01032496],
         [-0.0280284 , -0.03481358, -0.00225686]]], dtype=float32),
 array([[-0.0280284 , -0.03481358, -0.00225686]], dtype=float32),
 array([[-0.05565928, -0.06893536, -0.00460539]], dtype=float32)]

In [34]:
data = array([0.1, 0.2, 0.3, 0.4, 0]).reshape((1,5,1))
model.predict(data)

array([[-0.06046996,  0.03579271, -0.07271238]], dtype=float32)

In [35]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding

In [44]:
inputs1 = Input(shape=(5, 1))
# lstm1 = LSTM(3, return_sequences=True)(inputs1)
# lstm2 = LSTM(4)(lstm1)
lstm2 = LSTM(4)(inputs1)
dense1 = Dense(1, activation="sigmoid")(lstm2)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model = Model(inputs=inputs1, outputs=dense1)
model.summary()

Model: "model_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_21 (InputLayer)        [(None, 5, 1)]            0         
_________________________________________________________________
lstm_21 (LSTM)               (None, 4)                 96        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 5         
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


In [43]:
data = array([0.1, 0.2, 0.3, 0.4, 0]).reshape((1,5,1))
model.predict(data)

array([[0.5142799]], dtype=float32)